### ISSUE TITLE
Usage Tutorial

### ISSUE THREAD

**Issue by Ali-Khazaee** [yangkun19921001/DexEncryptionDecryption#5]
Can you provide step by step how to use it to encrypt APK?

**Comment by yangkun19921001** [comment]
@Ali-Khazaee 
1. clean project
2. Build the project (AS->Build->Rebuild Project)
3. Open proxy_tools/src/main/main.java file configuration, configure dx, zipalign, apksigner environment
4. Run the proxy_tools/src/main/main.java file
5. Get the signed file: app/build/outputs/apk/debug/app-signed-aligned.apk
